sudo: required

services:
  - docker 

before_install: 
  - docker build -f Dockerfile.dev -t my-app:dev .

script: 
  - docker run my-app:dev npm run test -- --run --coverage

deploy:
  provider: heroku
  api_key:
    secure: HRKU-7f304b1b-93d6-4b04-a452-70e0cba84ec1
