services:
  frontend:
    image: my-app:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - node_modules:/app/node_modules
      - ./:/app
    command: ['npm', 'run', 'dev']
    tty: true
    stdin_open: false

  testing:
    image: my-app:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev
    environment:
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    volumes:
      - node_modules:/app/node_modules
      - ./:/app
    command: ['npm', 'run', 'test']
    tty: true
    stdin_open: false

volumes:
  node_modules:
