FROM node:alpine

WORKDIR /app

COPY package.json .
# Set NODE_ENV to development before running npm install
ENV NODE_ENV=development
RUN npm install

# For Travis CLI
COPY . .

# For production
# COPY . .
# RUN npm run build
# CMD [ "npm", "start" ]
